export const scoutToSOMA: Record<string, string> = {
	bip_pelvis: 'Hips',
	bip_spine_0: 'Spine1',
	bip_spine_1: 'Spine2',
	bip_spine_2: 'Chest',
	bip_spine_3: '',
	bip_neck: 'Neck1',
	bip_head: 'Head',
	bip_collar_L: 'LeftShoulder',
	bip_collar_R: 'RightShoulder',
	bip_upperArm_L: 'LeftArm',
	bip_upperArm_R: 'RightArm',
	bip_lowerArm_L: 'LeftForeArm',
	bip_lowerArm_R: 'RightForeArm',
	bip_hip_L: 'LeftLeg',
	bip_hip_R: 'RightLeg',
	bip_knee_L: 'LeftShin',
	bip_knee_R: 'RightShin',
	bip_foot_L: 'LeftFoot',
	bip_foot_R: 'RightFoot',
	bip_hand_L: 'LeftHand',
	bip_hand_R: 'RightHand',
	bip_toe_L: 'LeftToeBase',
	bip_toe_R: 'RightToeBase',
	weapon_bone: '',
	weapon_bone_1: '',
	weapon_bone_2: '',
	weapon_bone_3: '',
	weapon_bone_4: '',
	weapon_bone_L: '',
	medal_bone: '',
	mvm: '',
	effect_hand_L: '',
	effect_hand_R: '',
	bip_dogtag_0: '',
	bip_dogtag_1: '',
	bip_dogtag_2: '',
	bip_dogtag_3: '',
	bip_packtop: '',
	bip_packmiddle: '',
	bip_thumb_0_L: 'LeftHandThumb1',
	bip_thumb_0_R: 'RightHandThumb1',
	bip_index_0_L: 'LeftHandIndex1',
	bip_index_0_R: 'RightHandIndex1',
	bip_middle_0_L: 'LeftHandMiddle1',
	bip_middle_0_R: 'RightHandMiddle1',
	bip_ring_0_L: 'LeftHandRing1',
	bip_ring_0_R: 'RightHandRing1',
	bip_pinky_0_L: 'LeftHandPinky1',
	bip_pinky_0_R: 'RightHandPinky1',
	bip_thumb_1_L: 'LeftHandThumb2',
	bip_thumb_1_R: 'RightHandThumb2',
	bip_index_1_L: 'LeftHandIndex2',
	bip_index_1_R: 'RightHandIndex2',
	bip_middle_1_L: 'LeftHandMiddle2',
	bip_middle_1_R: 'RightHandMiddle2',
	bip_ring_1_L: 'LeftHandRing3',
	bip_ring_1_R: 'RightHandRing3',
	bip_pinky_1_L: 'LeftHandPinky3',
	bip_pinky_1_R: 'RightHandPinky3',
	bip_thumb_2_L: 'LeftHandThumb3',
	bip_thumb_2_R: 'RightHandThumb3',
	bip_index_2_L: 'LeftHandIndex4',
	bip_index_2_R: 'RightHandIndex4',
	bip_middle_2_L: 'LeftHandMiddle4',
	bip_middle_2_R: 'RightHandMiddle4',
	bip_ring_2_L: 'LeftHandRingEnd',
	bip_ring_2_R: 'RightHandRing4',
	bip_pinky_2_L: 'LeftHandPinkyEnd',
	bip_pinky_2_R: 'RightHandPinkyEnd',
	prop_bone: '',
	prop_bone_1: '',
	prop_bone_2: '',
	prop_bone_3: '',
	prop_bone_4: '',
	prop_bone_5: '',
	prop_bone_6: '',
	hlp_forearm_L: '',
	hlp_forearm_R: '',
}


/*,
		['LeftShoulder', 'Chest'],
		['LeftArm', 'LeftShoulder'],
		['LeftForeArm', 'LeftArm'],
		['LeftHand', 'LeftForeArm'],
		['LeftHandThumb1', 'LeftHand'],
		['LeftHandThumb2', 'LeftHandThumb1'],
		['LeftHandThumb3', 'LeftHandThumb2'],
		['LeftHandThumbEnd', 'LeftHandThumb3'],
		['LeftHandIndex1', 'LeftHand'],
		['LeftHandIndex2', 'LeftHandIndex1'],
		['LeftHandIndex3', 'LeftHandIndex2'],
		['LeftHandIndex4', 'LeftHandIndex3'],
		['LeftHandIndexEnd', 'LeftHandIndex4'],
		['LeftHandMiddle1', 'LeftHand'],
		['LeftHandMiddle2', 'LeftHandMiddle1'],
		['LeftHandMiddle3', 'LeftHandMiddle2'],
		['LeftHandMiddle4', 'LeftHandMiddle3'],
		['LeftHandMiddleEnd', 'LeftHandMiddle4'],
		['LeftHandRing1', 'LeftHand'],
		['LeftHandRing2', 'LeftHandRing1'],
		['LeftHandRing3', 'LeftHandRing2'],
		['LeftHandRing4', 'LeftHandRing3'],
		['LeftHandRingEnd', 'LeftHandRing4'],
		['LeftHandPinky1', 'LeftHand'],
		['LeftHandPinky2', 'LeftHandPinky1'],
		['LeftHandPinky3', 'LeftHandPinky2'],
		['LeftHandPinky4', 'LeftHandPinky3'],
		['LeftHandPinkyEnd', 'LeftHandPinky4'],
		['RightShoulder', 'Chest'],
		['RightArm', 'RightShoulder'],
		['RightForeArm', 'RightArm'],
		['RightHand', 'RightForeArm'],
		['RightHandThumb1', 'RightHand'],
		['RightHandThumb2', 'RightHandThumb1'],
		['RightHandThumb3', 'RightHandThumb2'],
		['RightHandThumbEnd', 'RightHandThumb3'],
		['RightHandIndex1', 'RightHand'],
		['RightHandIndex2', 'RightHandIndex1'],
		['RightHandIndex3', 'RightHandIndex2'],
		['RightHandIndex4', 'RightHandIndex3'],
		['RightHandIndexEnd', 'RightHandIndex4'],
		['RightHandMiddle1', 'RightHand'],
		['RightHandMiddle2', 'RightHandMiddle1'],
		['RightHandMiddle3', 'RightHandMiddle2'],
		['RightHandMiddle4', 'RightHandMiddle3'],
		['RightHandMiddleEnd', 'RightHandMiddle4'],
		['RightHandRing1', 'RightHand'],
		['RightHandRing2', 'RightHandRing1'],
		['RightHandRing3', 'RightHandRing2'],
		['RightHandRing4', 'RightHandRing3'],
		['RightHandRingEnd', 'RightHandRing4'],
		['RightHandPinky1', 'RightHand'],
		['RightHandPinky2', 'RightHandPinky1'],
		['RightHandPinky3', 'RightHandPinky2'],
		['RightHandPinky4', 'RightHandPinky3'],
		['RightHandPinkyEnd', 'RightHandPinky4'],
		['LeftLeg', 'Hips'],
		['LeftShin', 'LeftLeg'],
		['LeftFoot', 'LeftShin'],
		['LeftToeBase', 'LeftFoot'],
		['LeftToeEnd', 'LeftToeBase'],
		['RightLeg', 'Hips'],
		['RightShin', 'RightLeg'],
		['RightFoot', 'RightShin'],
		['RightToeBase', 'RightFoot'],
		['RightToeEnd', 'RightToeBase'],
*/

let initialized = false;
const scout2SOMA: Record<string, string> = {}
export function somaToScout(name: string): string | undefined {
	if (!initialized) {
		initialized = true;
		for (const key in scoutToSOMA) {
			const value = scoutToSOMA[key]!;
			if (value !== '') {
				scout2SOMA[value] = key;
			}
		}
	}

	return scout2SOMA[name];
}
